2025-06-18T10:01:19.4366865Z ##[group]Run python -m pip install --upgrade pip
2025-06-18T10:01:19.4367352Z [36;1mpython -m pip install --upgrade pip[0m
2025-06-18T10:01:19.4367947Z [36;1mpip install -e .[dev][0m
2025-06-18T10:01:19.4471920Z shell: /usr/bin/bash -e {0}
2025-06-18T10:01:19.4472225Z env:
2025-06-18T10:01:19.4472501Z   pythonLocation: /opt/hostedtoolcache/Python/3.11.13/x64
2025-06-18T10:01:19.4473019Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.13/x64/lib/pkgconfig
2025-06-18T10:01:19.4473459Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.13/x64
2025-06-18T10:01:19.4474061Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.13/x64
2025-06-18T10:01:19.4474458Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.13/x64
2025-06-18T10:01:19.4474842Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.13/x64/lib
2025-06-18T10:01:19.4475167Z ##[endgroup]
2025-06-18T10:01:20.0826844Z Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages (25.1.1)
2025-06-18T10:01:20.6303422Z Obtaining file:///home/runner/work/Automatizacion_RSI_PCI/Automatizacion_RSI_PCI
2025-06-18T10:01:20.7341798Z ERROR: Exception:
2025-06-18T10:01:20.7342547Z Traceback (most recent call last):
2025-06-18T10:01:20.7352066Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
2025-06-18T10:01:20.7353120Z     status = _inner_run()
2025-06-18T10:01:20.7353446Z              ^^^^^^^^^^^^
2025-06-18T10:01:20.7354355Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
2025-06-18T10:01:20.7355292Z     return self.run(options, args)
2025-06-18T10:01:20.7355643Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7356548Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 68, in wrapper
2025-06-18T10:01:20.7357435Z     return func(self, options, args)
2025-06-18T10:01:20.7358028Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7358894Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 387, in run
2025-06-18T10:01:20.7359769Z     requirement_set = resolver.resolve(
2025-06-18T10:01:20.7360153Z                       ^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7361183Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 77, in resolve
2025-06-18T10:01:20.7362273Z     collected = self.factory.collect_root_requirements(root_reqs)
2025-06-18T10:01:20.7362792Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7363901Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 545, in collect_root_requirements
2025-06-18T10:01:20.7364949Z     reqs = list(
2025-06-18T10:01:20.7365209Z            ^^^^^
2025-06-18T10:01:20.7366296Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 501, in _make_requirements_from_install_req
2025-06-18T10:01:20.7367425Z     cand = self._make_base_candidate_from_link(
2025-06-18T10:01:20.7368009Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7369134Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 212, in _make_base_candidate_from_link
2025-06-18T10:01:20.7370346Z     self._editable_candidate_cache[link] = EditableCandidate(
2025-06-18T10:01:20.7370844Z                                            ^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7371873Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 331, in __init__
2025-06-18T10:01:20.7372839Z     super().__init__(
2025-06-18T10:01:20.7373841Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 159, in __init__
2025-06-18T10:01:20.7375276Z     self.dist = self._prepare()
2025-06-18T10:01:20.7375611Z                 ^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7376556Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 236, in _prepare
2025-06-18T10:01:20.7377553Z     dist = self._prepare_distribution()
2025-06-18T10:01:20.7378185Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7379490Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 341, in _prepare_distribution
2025-06-18T10:01:20.7380727Z     return self._factory.preparer.prepare_editable_requirement(self._ireq)
2025-06-18T10:01:20.7381291Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7382344Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 703, in prepare_editable_requirement
2025-06-18T10:01:20.7383383Z     dist = _get_prepared_distribution(
2025-06-18T10:01:20.7383752Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7384767Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
2025-06-18T10:01:20.7385805Z     abstract_dist.prepare_distribution_metadata(
2025-06-18T10:01:20.7386915Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 39, in prepare_distribution_metadata
2025-06-18T10:01:20.7388087Z     self.req.load_pyproject_toml()
2025-06-18T10:01:20.7389031Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 512, in load_pyproject_toml
2025-06-18T10:01:20.7389979Z     pyproject_toml_data = load_pyproject_toml(
2025-06-18T10:01:20.7390405Z                           ^^^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7391334Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pip/_internal/pyproject.py", line 70, in load_pyproject_toml
2025-06-18T10:01:20.7392228Z     pp_toml = tomllib.loads(f.read())
2025-06-18T10:01:20.7392602Z               ^^^^^^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7393274Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/tomllib/_parser.py", line 102, in loads
2025-06-18T10:01:20.7394072Z     pos = key_value_rule(src, pos, out, header, parse_float)
2025-06-18T10:01:20.7394575Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7395412Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/tomllib/_parser.py", line 326, in key_value_rule
2025-06-18T10:01:20.7396303Z     pos, key, value = parse_key_value_pair(src, pos, parse_float)
2025-06-18T10:01:20.7396861Z                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7397942Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/tomllib/_parser.py", line 369, in parse_key_value_pair
2025-06-18T10:01:20.7398787Z     pos, value = parse_value(src, pos, parse_float)
2025-06-18T10:01:20.7399220Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-18T10:01:20.7399997Z   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/tomllib/_parser.py", line 649, in parse_value
2025-06-18T10:01:20.7400817Z     raise suffixed_err(src, pos, "Invalid value")
2025-06-18T10:01:20.7401386Z tomllib.TOMLDecodeError: Invalid value (at line 6, column 17)
2025-06-18T10:01:20.7740969Z ##[error]Process completed with exit code 2.
